import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
import LogoutPage from "../components/logout";
import { ThemeProvider } from "@gravity-ui/uikit";
import "@gravity-ui/uikit/styles/fonts.css";
import "@gravity-ui/uikit/styles/styles.css";
import { Grid } from "@gravity-ui/page-constructor";
import ThemeS from '../components/ThemeS'
import GroupNav from './GroupNav/GroupNav';
import { LanguageProvider } from '../components/languageContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Torus Components',
  description: '"Generated by Torus'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <LanguageProvider>
      <div className=' relative h-[100vh] w-[100vw] '>
        <ThemeS>
          <GroupNav />
          <ThemeProvider theme='light'>
              <main>{children}</main>
          </ThemeProvider>
        </ThemeS>
        <ToastContainer />
      </div>
    </LanguageProvider>
  )
}
